// Module: language
// Discrption: This module will contain all the language settings for the script.
// Last Updated: 2024/12/23

let language = {
  module: "language",
  settingActiveLanguage: "en",
  dropdownValueNewLanguage: "",
  languages: ["en", "nl", "us", "fr", "de", "gr", "pl", "es"],

  nl: {
    about: "Over",
    active: "Actief",
    alliance: "Alliantie",
    allianceDataAvailable: "Alliantie data beschikbaar. Alliantie: ",
    allianceName: "Alliantie naam",
    allianceNumberPlayers: "Aantal alliantie leden",
    alliancePoints: "Alliantie punten",
    allianceRank: "Alliantie rank",
    and: "En",
    attackNotification: "Animeer het browser icoon bij een aanval",
    battlePoints: "Gevechtspunten",
    bbcodeAlliance: "Kopieer de informatie van alle leden van de alliantie",
    bbcodeAllianceCopySucces: "BBCode - Alliantie informatie is gekopieerd",
    bbcodeIsland: "Kopieer de informatie van dit eiland",
    bbcodeIslandCopyFail:
      "BBCode - Eiland is leeg, informatie is niet gekopieerd",
    bbcodeIslandCopySucces: "BBCode - Eiland informatie is gekopieerd",
    bbcodePlayer: "Kopieer de informatie van deze speler",
    bbcodePlayerCopySucces: "BBCode - Speler informatie is gekopieerd",
    bbcodeWindowTitle: "GrepoTools - BBCode - Plakken gegevens",
    button: "Knop",
    changes: "Veranderingen",
    cityRequired: "De stad wordt automatisch toegevoegd, dit veld is verplicht",
    color: "Kleur",
    coordinates: "Coördinaten",
    day: "dag",
    dayMode: "Dag mode",
    days: "dagen",
    donation: "Donatie",
    emptyColumn: "Lege kolom",
    farmerIslandNumbersTextColor: "Boerendorp eiland tekst kleur",
    farmerVillageIslandNumbers: "Boerendorp eilandnummers",
    farmerVillageIslandTags: "Boerendorp eilandtags",
    free: "Vrij",
    general: "Algemene",
    ghostTown: "Spookstad",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Grepotools Update beschikbaar",
    grepolisRank: "Grepolis rank",
    grepolisScore: "Grepolis score",
    grid: "Raster",
    heroIcon: "Held icoon in stadsoverzicht",
    hide: "Verberg",
    hour: "uur",
    inactiveTimePlayer: "Speler inactiviteit (samenwerking met GrepoData)",
    island: "Eiland",
    islandDataAvailable: "Eiland data beschikbaar. Eiland: ",
    islandEmptyNoMessage:
      "Het eiland is leeg, er kan geen bericht worden verzonden",
    islandInformationWindow: "Eiland informatie venster",
    islandLinkIslandInfo: "eiland nummers/tags als link naar eiland informatie",
    islandNoAllianceNoMessage:
      "Op dit eiland zijn geen aliantieleden aanwezig, er kan geen bericht worden verzonden",
    islandNumber: "Eiland nummer",
    islandNumbersTags: "Eiland nummers / tags",
    islandOccupation: "Eiland bezetting",
    islandTag: "Eiland tag",
    islandView: "Eiland overzicht",
    joinBetaTesting: "Deelnemen aan het bètatestprogramma",
    language: "Taal",
    mapTags: "Map tags",
    maxMembers: "Maximaal aantal leden",
    member: "Lid",
    members: "Leden",
    message: "Bericht",
    nightMode: "Nacht mode",
    noDataAvailable: "GrepoTools BBCode - Geen data beschikbaar",
    noWrap: "Toon grote tags op één regel",
    number: "Nummer",
    numberShort: "Nr",
    occupied: "Bezet",
    ocean: "Oceaan",
    oceanGrid: "Oceaan raster",
    oceanNumbers: "Oceaan nummers",
    of: "Van",
    otherScripts: "Andere scripts",
    page: "Pagina",
    pasteData: "Gegevens plakken",
    player: "Speler",
    playerDataAvailable: "Speler data beschikbaar. Speler: ",
    playerName: "Spelersnaam",
    playerRequired:
      "De speler wordt automatisch toegevoegd, dit veld is verplicht",
    points: "Punten",
    rank: "Rank",
    resources: "Resources",
    rockIslandNumbers: "Rots eilandnummers",
    rockIslandNumbersTextColor: "Rots eiland tekst kleur",
    safe: "Opslaan",
    safeAndReload: "Opslaan en herladen",
    safeFail: "GrepoTools instellingen zijn niet succesvol opgeslagen",
    safeSuccess: "GrepoTools instellingen zijn succesvol opgeslagen",
    script: "Grepolis GrepoTools Script",
    selectPage: "Selecteer pagina:",
    sendMessageAlliance: "Verstuur bericht aan alle leden van de alliantie",
    sendMessageIsland:
      "Verstuur bericht aan alle leden van de alliantie op het eiland",
    settings: "Instellingen",
    show: "Toon",
    showInfoAboveTable: "Toon de informatie hieronder boven de tabel",
    showInfoInTable: "Toon de informatie hieronder in de tabel",
    silver: "Zilver",
    spellsHarborBarracks: "Spreuken in de haven en de kazerne",
    stone: "Steen",
    strategicMap: "Strategische kaart",
    text: "Tekst",
    to: "Naar",
    town: "Stad",
    townName: "Stadsnaam",
    townPoints: "Stad punten",
    towns: "Steden",
    update: "Update",
    version: "Versie",
    whileScrolling: "tijdens scrollen",
    wood: "Hout",
    world: "Wereld",

    colors: {
      blue: "blauw",
      brown: "bruin",
      green: "groen",
      grey: "grijs",
      lightblue: "licht blauw",
      lightgreen: "licht groen",
      lightred: "licht rood",
      pink: "roze",
      purple: "paars",
      red: "rood",
      white: "wit",
      yellow: "geel",
    },

    languages: {
      de: "Duits",
      en: "Engels",
      es: "Spaans",
      fr: "Frans",
      gr: "Grieks",
      nl: "Nederlands",
      pl: "Pools",
      us: "Amerikaans",
    },
  },

  en: {
    about: "About",
    active: "Active",
    alliance: "Alliance",
    allianceDataAvailable: "Alliance data available. Alliance: ",
    allianceName: "Alliance name",
    allianceNumberPlayers: "Number of alliance members",
    alliancePoints: "Alliance points",
    allianceRank: "Alliance rank",
    and: "And",
    attackNotification: "Animate the browser icon during an attack",
    battlePoints: "Battle points",
    bbcodeAlliance: "Copy the information of all alliance members",
    bbcodeAllianceCopySucces: "BBCode - Alliance information is copied",
    bbcodeIsland: "Copy the information of this island",
    bbcodeIslandCopyFail: "BBCode - Island is empty, information is not copied",
    bbcodeIslandCopySucces: "BBCode - Island information is copied",
    bbcodePlayer: "Copy the information of this player",
    bbcodePlayerCopySucces: "BBCode - Player information is copied",
    bbcodeWindowTitle: "GrepoTools - BBCode - Paste data",
    button: "Button",
    changes: "Changes",
    cityRequired: "The city is automatically added, this field is required",
    color: "Color",
    coordinates: "Coördinates",
    day: "day",
    dayMode: "Day mode",
    days: "days",
    donation: "Donations",
    emptyColumn: "Empty column",
    farmerIslandNumbersTextColor: "Farmer island text color",
    farmerVillageIslandNumbers: "Farmer village island numbers",
    farmerVillageIslandTags: "Farmer village island tags",
    free: "Free",
    general: "General",
    ghostTown: "Ghost town",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Grepotools Update available",
    grepolisRank: "Grepolis rank",
    grepolisScore: "Grepolis score",
    grid: "Grid",
    heroIcon: "Hero icon in city overview",
    hide: "Hide",
    hour: "hour",
    inactiveTimePlayer: "Player inactivity (collaboration with GrepoData)",
    island: "Island",
    islandDataAvailable: "Island data available. Island: ",
    islandEmptyNoMessage: "The island is empty, no message can be sent",
    islandInformationWindow: "Island information window",
    islandLinkIslandInfo: "island numbers/tags as link to island information",
    islandNoAllianceNoMessage:
      "There are no alliance members on this island, no message can be sent",
    islandNumber: "Island number",
    islandNumbersTags: "Island numbers / tags",
    islandOccupation: "Island occupation",
    islandTag: "Island tag",
    islandView: "Island View",
    joinBetaTesting: "Join the beta testing program",
    language: "Language",
    mapTags: "Map tags",
    maxMembers: "Maximum number of members",
    member: "Member",
    members: "Members",
    message: "Message",
    nightMode: "Night mode",
    noDataAvailable: "GrepoTools BBCode - No data available",
    noWrap: "Show large tags on one line",
    number: "Number",
    numberShort: "No",
    occupied: "Occupied",
    ocean: "Ocean",
    oceanGrid: "Ocean grid",
    oceanNumbers: "Ocean numbers",
    of: "Of",
    otherScripts: "Other scripts",
    page: "Page",
    pasteData: "Paste data",
    player: "Player",
    playerDataAvailable: "Player data available. Player: ",
    playerName: "Player name",
    playerRequired: "The player is automatically added, this field is required",
    points: "Points",
    rank: "Rank",
    resources: "Resources",
    rockIslandNumbers: "Rock island numbers",
    rockIslandNumbersTextColor: "Rock island text color",
    safe: "Save",
    safeAndReload: "Save and reload",
    safeFail: "GrepoTools settings have not been successfully saved",
    safeSuccess: "GrepoTools settings have been successfully saved",
    script: "Grepolis GrepoTools Script",
    selectPage: "Select page:",
    sendMessageAlliance: "Send message to all alliance members",
    sendMessageIsland: "Send message to all alliance members on the island",
    settings: "Settings",
    show: "Show",
    showInfoAboveTable: "Show the information below above the table",
    showInfoInTable: "Show the information below in the table",
    silver: "Silver",
    spellsHarborBarracks: "Spells in the harbor and the barracks",
    stone: "Stone",
    strategicMap: "Strategic map",
    text: "text",
    to: "To",
    town: "Town",
    townName: "Town name",
    townPoints: "Town points",
    towns: "Towns",
    update: "Update",
    version: "Version",
    whileScrolling: "while scrolling",
    wood: "Wood",
    world: "World",

    colors: {
      blue: "blue",
      brown: "brown",
      green: "green",
      grey: "grey",
      lightblue: "light blue",
      lightgreen: "light green",
      lightred: "light red",
      pink: "rose",
      purple: "purple",
      red: "red",
      white: "white",
      yellow: "yellow",
    },

    languages: {
      de: "German",
      en: "English",
      es: "Spanish",
      fr: "French",
      gr: "Greek",
      nl: "Dutch",
      pl: "Polish",
      us: "American",
    },
  },

  de: {
    about: "Über",
    active: "Aktiv",
    alliance: "Allianz",
    allianceDataAvailable: "Allianzdaten verfügbar. Allianz: ",
    allianceName: "Allianzname",
    allianceNumberPlayers: "Anzahl der Allianzenmitglieder",
    alliancePoints: "Allianzpunkte",
    allianceRank: "Allianzrang",
    and: "Und",
    attackNotification:
      "Animieren Sie das Browser-Symbol während eines Angriffs",
    battlePoints: "Kampfpunkte",
    bbcodeAlliance: "Kopieren Sie die Informationen aller Allianzenmitglieder",
    bbcodeAllianceCopySucces: "BBCode - Allianzinformationen wurden kopiert",
    bbcodeIsland: "Kopieren Sie die Informationen dieser Insel",
    bbcodeIslandCopyFail:
      "BBCode - Insel ist leer, Informationen wurden nicht kopiert",
    bbcodeIslandCopySucces: "BBCode - Inselinformationen wurden kopiert",
    bbcodePlayer: "Kopieren Sie die Informationen dieses Spielers",
    bbcodePlayerCopySucces: "BBCode - Spielerinformationen wurden kopiert",
    bbcodeWindowTitle: "GrepoTools - BBCode - Daten einfügen",
    button: "Knopf",
    changes: "Änderungen",
    cityRequired:
      "Die Stadt wird automatisch hinzugefügt, dieses Feld ist erforderlich",
    color: "Farbe",
    coordinates: "Koordinaten",
    day: "Tag",
    dayMode: "Tagmodus",
    days: "Tage",
    donation: "Spenden",
    emptyColumn: "Leere Spalte",
    farmerIslandNumbersTextColor: "Bauerninsel Textfarbe",
    farmerVillageIslandNumbers: "Bauerninselnummern",
    farmerVillageIslandTags: "Bauerninseltags",
    free: "Frei",
    general: "Allgemein",
    ghostTown: "Geisterstadt",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Grepotools Update verfügbar",
    grepolisRank: "Grepolis Rang",
    grepolisScore: "Grepolis Punktzahl",
    grid: "Raster",
    heroIcon: "Helden-Symbol in der Stadtübersicht",
    hide: "Verstecken",
    hour: "Stunde",
    inactiveTimePlayer: "Spieler Inaktivität (Zusammenarbeit mit GrepoData)",
    island: "Insel",
    islandDataAvailable: "Insel Daten verfügbar. Insel: ",
    islandEmptyNoMessage:
      "Die Insel ist leer, es kann keine Nachricht gesendet werden",
    islandInformationWindow: "Inselinformationsfenster",
    islandLinkIslandInfo: "Inselnummern/tags als Link zu Inselinformationen",
    islandNoAllianceNoMessage:
      "Es gibt keine Allianzenmitglieder auf dieser Insel, es kann keine Nachricht gesendet werden",
    islandNumber: "Inselnummer",
    islandNumbersTags: "Inselnummern / tags",
    islandOccupation: "Inselbesetzung",
    islandTag: "Insel tag",
    islandView: "Inselansicht",
    language: "Sprache",
    joinBetaTesting: "Am Beta-Testprogramm teilnehmen",
    mapTags: "Kartentags",
    maxMembers: "Maximale Anzahl von Mitgliedern",
    member: "Mitglied",
    members: "Mitglieder",
    message: "Nachricht",
    nightMode: "Nachtmodus",
    noDataAvailable: "GrepoTools BBCode - Keine Daten verfügbar",
    noWrap: "Große Tags in einer Zeile anzeigen",
    number: "Nummer",
    numberShort: "Nr",
    occupied: "Besetzt",
    ocean: "Ozean",
    oceanGrid: "Ozeanraster",
    oceanNumbers: "Ozeannummern",
    of: "Von",
    otherScripts: "Andere Skripte",
    page: "Seite",
    pasteData: "Daten einfügen",
    player: "Spieler",
    playerDataAvailable: "Spielerdaten verfügbar. Spieler: ",
    playerName: "Spielername",
    playerRequired:
      "Der Spieler wird automatisch hinzugefügt, dieses Feld ist erforderlich",
    points: "Punkte",
    rank: "Rang",
    resources: "Ressourcen",
    rockIslandNumbers: "Felseninselnummern",
    rockIslandNumbersTextColor: "Felseninsel Textfarbe",
    safe: "Speichern",
    safeAndReload: "Speichern und neu laden",
    safeFail: "GrepoTools Einstellungen wurden nicht erfolgreich gespeichert",
    safeSuccess: "GrepoTools Einstellungen wurden erfolgreich gespeichert",
    script: "Grepolis GrepoTools Skript",
    selectPage: "Seite auswählen:",
    sendMessageAlliance: "Nachricht an alle Allianzenmitglieder senden",
    sendMessageIsland:
      "Nachricht an alle Allianzenmitglieder auf der Insel senden",
    settings: "Einstellungen",
    show: "Anzeigen",
    showInfoAboveTable:
      "Zeigen Sie die Informationen unten über der Tabelle an",
    showInfoInTable: "Zeigen Sie die Informationen unten in der Tabelle an",
    silver: "Silber",
    spellsHarborBarracks: "Zauber im Hafen und in den Kasernen",
    stone: "Stein",
    strategicMap: "Strategische Karte",
    text: "Text",
    to: "Zu",
    town: "Stadt",
    townName: "Stadtname",
    townPoints: "Stadtpunkte",
    towns: "Städte",
    update: "Aktualisieren",
    version: "Version",
    whileScrolling: "während des Scrollens",
    wood: "Holz",
    world: "Welt",

    colors: {
      blue: "blau",
      brown: "braun",
      green: "grün",
      grey: "grau",
      lightblue: "hellblau",
      lightgreen: "hellgrün",
      lightred: "hellrot",
      pink: "rosa",
      purple: "lila",
      red: "rot",
      white: "weiß",
      yellow: "gelb",
    },

    languages: {
      de: "Deutsch",
      en: "Englisch",
      es: "Spanisch",
      fr: "Französisch",
      gr: "Griechisch",
      nl: "Niederländisch",
      pl: "Polnisch",
      us: "Amerikanisch",
    },
  },

  fr: {
    about: "À propos",
    active: "Actif",
    alliance: "Alliance",
    allianceDataAvailable: "Données de l'alliance disponibles. Alliance : ",
    allianceName: "Nom de l'alliance",
    allianceNumberPlayers: "Nombre de membres de l'alliance",
    alliancePoints: "Points de l'alliance",
    allianceRank: "Rang de l'alliance",
    and: "Et",
    attackNotification: "Animer l'icône du navigateur pendant une attaque",
    battlePoints: "Points de bataille",
    bbcodeAlliance: "Copier les informations de tous les membres de l'alliance",
    bbcodeAllianceCopySucces: "BBCode - Informations de l'alliance copiées",
    bbcodeIsland: "Copier les informations de cette île",
    bbcodeIslandCopyFail:
      "BBCode - L'île est vide, les informations ne sont pas copiées",
    bbcodeIslandCopySucces: "BBCode - Informations de l'île copiées",
    bbcodePlayer: "Copier les informations de ce joueur",
    bbcodePlayerCopySucces: "BBCode - Informations du joueur copiées",
    bbcodeWindowTitle: "GrepoTools - BBCode - Coller des données",
    button: "Bouton",
    changes: "Changements",
    cityRequired: "La ville est automatiquement ajoutée, ce champ est requis",
    color: "Couleur",
    coordinates: "Coordonnées",
    day: "jour",
    dayMode: "Mode jour",
    days: "jours",
    donation: "Dons",
    emptyColumn: "Colonne vide",
    farmerIslandNumbersTextColor:
      "Couleur du texte des numéros d'île de fermier",
    farmerVillageIslandNumbers: "Numéros d'île de village de fermier",
    farmerVillageIslandTags: "Tags d'île de village de fermier",
    free: "Gratuit",
    general: "Général",
    ghostTown: "Ville fantôme",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Mise à jour Grepotools disponible",
    grepolisRank: "Rang Grepolis",
    grepolisScore: "Score Grepolis",
    grid: "Grille",
    heroIcon: "Icône du héros dans l'aperçu de la ville",
    hide: "Cacher",
    hour: "heure",
    inactiveTimePlayer: "Inactivité du joueur (collaboration avec GrepoData)",
    island: "Île",
    islandDataAvailable: "Données de l'île disponibles. Île : ",
    islandEmptyNoMessage: "L'île est vide, aucun message ne peut être envoyé",
    islandInformationWindow: "Fenêtre d'information sur l'île",
    islandLinkIslandInfo:
      "numéros/tags d'île comme lien vers les informations de l'île",
    islandNoAllianceNoMessage:
      "Il n'y a pas de membres de l'alliance sur cette île, aucun message ne peut être envoyé",
    islandNumber: "Numéro de l'île",
    islandNumbersTags: "Numéros / tags de l'île",
    islandOccupation: "Occupation de l'île",
    islandTag: "Tag de l'île",
    islandView: "Vue de l'île",
    joinBetaTesting: "Rejoindre le programme de test bêta",
    language: "Langue",
    mapTags: "Tags de carte",
    maxMembers: "Nombre maximum de membres",
    member: "Membre",
    members: "Membres",
    message: "Message",
    nightMode: "Mode nuit",
    noDataAvailable: "GrepoTools BBCode - Aucune donnée disponible",
    noWrap: "Afficher les grands tags sur une seule ligne",
    number: "Numéro",
    numberShort: "N°",
    occupied: "Occupé",
    ocean: "Océan",
    oceanGrid: "Grille de l'océan",
    oceanNumbers: "Numéros de l'océan",
    of: "De",
    otherScripts: "Autres scripts",
    page: "Page",
    pasteData: "Coller des données",
    player: "Joueur",
    playerDataAvailable: "Données du joueur disponibles. Joueur : ",
    playerName: "Nom du joueur",
    playerRequired: "Le joueur est automatiquement ajouté, ce champ est requis",
    points: "Points",
    rank: "Rang",
    resources: "Ressources",
    rockIslandNumbers: "Numéros d'île rocheuse",
    rockIslandNumbersTextColor: "Couleur du texte des numéros d'île rocheuse",
    safe: "Enregistrer",
    safeAndReload: "Enregistrer et recharger",
    safeFail:
      "Les paramètres de GrepoTools n'ont pas été enregistrés avec succès",
    safeSuccess: "Les paramètres de GrepoTools ont été enregistrés avec succès",
    script: "Script Grepolis GrepoTools",
    selectPage: "Sélectionner la page :",
    sendMessageAlliance: "Envoyer un message à tous les membres de l'alliance",
    sendMessageIsland:
      "Envoyer un message à tous les membres de l'alliance sur l'île",
    settings: "Paramètres",
    show: "Afficher",
    showInfoAboveTable:
      "Afficher les informations ci-dessous au-dessus de la table",
    showInfoInTable: "Afficher les informations ci-dessous dans la table",
    silver: "Argent",
    spellsHarborBarracks: "des sorts dans le port et la caserne",
    stone: "Pierre",
    strategicMap: "Carte stratégique",
    text: "Texte",
    to: "À",
    town: "Ville",
    townName: "Nom de la ville",
    townPoints: "Points de la ville",
    towns: "Villes",
    update: "Mettre à jour",
    version: "Version",
    whileScrolling: "pendant le défilement",
    wood: "Bois",
    world: "Monde",

    colors: {
      blue: "bleu",
      brown: "marron",
      green: "vert",
      grey: "gris",
      lightblue: "bleu clair",
      lightgreen: "vert clair",
      lightred: "rouge clair",
      pink: "rose",
      purple: "violet",
      red: "rouge",
      white: "blanc",
      yellow: "jaune",
    },

    languages: {
      de: "Allemand",
      en: "Anglais",
      es: "Espagnol",
      fr: "Français",
      gr: "Grec",
      nl: "Néerlandais",
      pl: "Polonais",
      us: "Américain",
    },
  },

  gr: {
    about: "Σχετικά",
    active: "Ενεργός",
    alliance: "Συμμαχία",
    allianceDataAvailable: "Δεδομένα συμμαχίας διαθέσιμα. Συμμαχία: ",
    allianceName: "Όνομα συμμαχίας",
    allianceNumberPlayers: "Αριθμός μελών συμμαχίας",
    alliancePoints: "Πόντοι συμμαχίας",
    allianceRank: "Βαθμός συμμαχίας",
    and: "Και",
    attackNotification:
      "Αναπαραγωγή του εικονιδίου του προγράμματος περιήγησης κατά τη διάρκεια μιας επίθεσης",
    battlePoints: "Πόντοι μάχης",
    bbcodeAlliance: "Αντιγραφή των πληροφοριών όλων των μελών της συμμαχίας",
    bbcodeAllianceCopySucces:
      "BBCode - Οι πληροφορίες της συμμαχίας αντιγράφηκαν",
    bbcodeIsland: "Αντιγραφή των πληροφοριών αυτού του νησιού",
    bbcodeIslandCopyFail:
      "BBCode - Το νησί είναι άδειο, οι πληροφορίες δεν αντιγράφηκαν",
    bbcodeIslandCopySucces: "BBCode - Οι πληροφορίες του νησιού αντιγράφηκαν",
    bbcodePlayer: "Αντιγραφή των πληροφοριών αυτού του παίκτη",
    bbcodePlayerCopySucces: "BBCode - Οι πληροφορίες του παίκτη αντιγράφηκαν",
    bbcodeWindowTitle: "GrepoTools - BBCode - Επικόλληση δεδομένων",
    button: "Κουμπί",
    changes: "Αλλαγές",
    cityRequired:
      "Η πόλη προστίθεται αυτόματα, αυτό το πεδίο είναι υποχρεωτικό",
    color: "Χρώμα",
    coordinates: "Συντεταγμένες",
    day: "ημέρα",
    dayMode: "Λειτουργία ημέρας",
    days: "ημέρες",
    donation: "Δωρεές",
    emptyColumn: "Κενή στήλη",
    farmerIslandNumbersTextColor: "Χρώμα κειμένου αριθμών νησιού αγρότη",
    farmerVillageIslandNumbers: "Αριθμοί νησιού χωριού αγρότη",
    farmerVillageIslandTags: "Ετικέτες νησιού χωριού αγρότη",
    free: "Δωρεάν",
    general: "Γενικός",
    ghostTown: "Πόλη φάντασμα",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Διαθέσιμη ενημέρωση Grepotools",
    grepolisRank: "Βαθμός Grepolis",
    grepolisScore: "Σκορ Grepolis",
    grid: "Πλέγμα",
    heroIcon: "Εικονίδιο ήρωα στην επισκόπηση πόλης",
    hide: "Απόκρυψη",
    hour: "ώρα",
    inactiveTimePlayer: "Αδράνεια παίκτη (συνεργασία με GrepoData)",
    island: "Νησί",
    islandDataAvailable: "Δεδομένα νησιού διαθέσιμα. Νησί: ",
    islandEmptyNoMessage: "Το νησί είναι άδειο, δεν μπορεί να σταλεί μήνυμα",
    islandInformationWindow: "Παράθυρο πληροφοριών νησιού",
    islandLinkIslandInfo:
      "αριθμοί/ετικέτες νησιού ως σύνδεσμος προς τις πληροφορίες του νησιού",
    islandNoAllianceNoMessage:
      "Δεν υπάρχουν μέλη της συμμαχίας σε αυτό το νησί, δεν μπορεί να σταλεί μήνυμα",
    islandNumber: "Αριθμός νησιού",
    islandNumbersTags: "Αριθμοί / ετικέτες νησιού",
    islandOccupation: "Κατοχή νησιού",
    islandTag: "Ετικέτα νησιού",
    islandView: "Προβολή νησιού",
    joinBetaTesting: "Συμμετο",
    language: "Γλώσσα",
    mapTags: "Ετικέτες χάρτη",
    maxMembers: "Μέγιστος αριθμός μελών",
    member: "Μέλος",
    members: "Μέλη",
    message: "Μήνυμα",
    nightMode: "Λειτουργία νύχτας",
    noDataAvailable: "GrepoTools BBCode - Δεν υπάρχουν διαθέσιμα δεδομένα",
    noWrap: "Εμφάνιση μεγάλων ετικετών σε μία γραμμή",
    number: "Αριθμός",
    numberShort: "Αρ.",
    occupied: "Κατειλημμένο",
    ocean: "Ωκεανός",
    oceanGrid: "Πλέγμα ωκεανού",
    oceanNumbers: "Αριθμοί ωκεανού",
    of: "Του",
    otherScripts: "Άλλα σενάρια",
    page: "Σελίδα",
    pasteData: "Επικόλληση δεδομένων",
    player: "Παίκτης",
    playerDataAvailable: "Δεδομένα παίκτη διαθέσιμα. Παίκτης: ",
    playerName: "Όνομα παίκτη",
    playerRequired:
      "Ο παίκτης προστίθεται αυτόματα, αυτό το πεδίο είναι υποχρεωτικό",
    points: "Πόντοι",
    rank: "Βαθμός",
    resources: "Πόροι",
    rockIslandNumbers: "Αριθμοί βραχώδους νησιού",
    rockIslandNumbersTextColor: "Χρώμα κειμένου αριθμών βραχώδους νησιού",
    safe: "Αποθήκευση",
    safeAndReload: "Αποθήκευση και επαναφόρτωση",
    safeFail: "Οι ρυθμίσεις του GrepoTools δεν αποθηκεύτηκαν με επιτυχία",
    safeSuccess: "Οι ρυθμίσεις του GrepoTools αποθηκεύτηκαν με επιτυχία",
    script: "Σενάριο Grepolis GrepoTools",
    selectPage: "Επιλογή σελίδας:",
    sendMessageAlliance: "Αποστολή μηνύματος σε όλα τα μέλη της συμμαχίας",
    sendMessageIsland:
      "Αποστολή μηνύματος σε όλα τα μέλη της συμμαχίας στο νησί",
    settings: "Ρυθμίσεις",
    show: "Εμφάνιση",
    showInfoAboveTable: "Εμφάνιση των πληροφοριών παρακάτω πάνω από τον πίνακα",
    showInfoInTable: "Εμφάνιση των πληροφοριών παρακάτω στον πίνακα",
    silver: "Ασήμι",
    spellsHarborBarracks: "Μαγείες στο λιμάνι και στις στρατώνες",
    stone: "Πέτρα",
    strategicMap: "Στρατηγικός χάρτης",
    text: "κείμενο",
    to: "Προς",
    town: "Πόλη",
    townName: "Όνομα πόλης",
    townPoints: "Πόντοι πόλης",
    towns: "Πόλεις",
    update: "Ενημέρωση",
    version: "Έκδοση",
    whileScrolling: "κατά τη διάρκεια της κύλισης",
    wood: "Ξύλο",
    world: "Κόσμος",

    colors: {
      blue: "μπλε",
      brown: "καφέ",
      green: "πράσινο",
      grey: "γκρι",
      lightblue: "γαλάζιο",
      lightgreen: "ανοιχτό πράσινο",
      lightred: "ανοιχτό κόκκινο",
      pink: "ροζ",
      purple: "μωβ",
      red: "κόκκινο",
      white: "λευκό",
      yellow: "κίτρινο",
    },

    languages: {
      de: "Γερμανικά",
      en: "Αγγλικά",
      es: "Ισπανικά",
      fr: "Γαλλικά",
      gr: "Ελληνικά",
      nl: "Ολλανδικά",
      pl: "Πολωνικ",
      us: "Αμερικανικά",
    },
  },

  pl: {
    about: "O",
    active: "Aktywny",
    alliance: "Sojusz",
    allianceDataAvailable: "Dane sojuszu dostępne. Sojusz: ",
    allianceName: "Nazwa sojuszu",
    allianceNumberPlayers: "Liczba członków sojuszu",
    alliancePoints: "Punkty sojuszu",
    allianceRank: "Ranga sojuszu",
    and: "I",
    attackNotification: "Animuj ikonę przeglądarki podczas ataku",
    battlePoints: "Punkty bitewne",
    bbcodeAlliance: "Skopiuj informacje o wszystkich członkach sojuszu",
    bbcodeAllianceCopySucces:
      "BBCode - Informacje o sojuszu zostały skopiowane",
    bbcodeIsland: "Skopiuj informacje o tej wyspie",
    bbcodeIslandCopyFail:
      "BBCode - Wyspa jest pusta, informacje nie zostały skopiowane",
    bbcodeIslandCopySucces: "BBCode - Informacje o wyspie zostały skopiowane",
    bbcodePlayer: "Skopiuj informacje o tym graczu",
    bbcodePlayerCopySucces: "BBCode - Informacje o graczu zostały skopiowane",
    bbcodeWindowTitle: "GrepoTools - BBCode - Wklej dane",
    button: "Przycisk",
    changes: "Zmiany",
    cityRequired: "Miasto jest automatycznie dodawane, to pole jest wymagane",
    color: "Kolor",
    coordinates: "Współrzędne",
    day: "dzień",
    dayMode: "Tryb dnia",
    days: "dni",
    donation: "Darowizny",
    emptyColumn: "Pusta kolumna",
    farmerIslandNumbersTextColor: "Kolor tekstu numerów wysp rolników",
    farmerVillageIslandNumbers: "Numery wysp wioski rolników",
    farmerVillageIslandTags: "Tagi wysp wioski rolników",
    free: "Darmowy",
    general: "Ogólny",
    ghostTown: "Miasto duchów",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Dostępna aktualizacja Grepotools",
    grepolisRank: "Ranga Grepolis",
    grepolisScore: "Wynik Grepolis",
    grid: "Siatka",
    heroIcon: "Ikona bohatera w przeglądzie miasta",
    hide: "Ukryj",
    hour: "godzina",
    inactiveTimePlayer: "Nieaktywność gracza (współpraca z GrepoData)",
    island: "Wyspa",
    islandDataAvailable: "Dane wyspy dostępne. Wyspa: ",
    islandEmptyNoMessage: "Wyspa jest pusta, nie można wysłać wiadomości",
    islandInformationWindow: "Okno informacji o wyspie",
    islandLinkIslandInfo: "numery/tagi wysp jako link do informacji o wyspie",
    islandNoAllianceNoMessage:
      "Na tej wyspie nie ma członków sojuszu, nie można wysłać wiadomości",
    islandNumber: "Numer wyspy",
    islandNumbersTags: "Numery / tagi wysp",
    islandOccupation: "Zajęcie wyspy",
    islandTag: "Tag wyspy",
    islandView: "Widok wyspy",
    joinBetaTesting: "Dołącz do programu testów beta",
    language: "Język",
    mapTags: "Tagi mapy",
    maxMembers: "Maksymalna liczba członków",
    member: "Członek",
    members: "Członkowie",
    message: "Wiadomość",
    nightMode: "Tryb nocny",
    noDataAvailable: "GrepoTools BBCode - Brak dostępnych danych",
    noWrap: "Pokaż duże tagi w jednej linii",
    number: "Numer",
    numberShort: "Nr",
    occupied: "Zajęty",
    ocean: "Ocean",
    oceanGrid: "Siatka oceanu",
    oceanNumbers: "Numery oceanu",
    of: "Z",
    otherScripts: "Inne skrypty",
    page: "Strona",
    pasteData: "Wklej dane",
    player: "Gracz",
    playerDataAvailable: "Dane gracza dostępne. Gracz: ",
    playerName: "Nazwa gracza",
    playerRequired: "Gracz jest automatycznie dodawany, to pole jest wymagane",
    points: "Punkty",
    rank: "Ranga",
    resources: "Zasoby",
    rockIslandNumbers: "Numery skalistych wysp",
    rockIslandNumbersTextColor: "Kolor tekstu numerów skalistych wysp",
    safe: "Zapisz",
    safeAndReload: "Zapisz i przeładuj",
    safeFail: "Ustawienia GrepoTools nie zostały pomyślnie zapisane",
    safeSuccess: "Ustawienia GrepoTools zostały pomyślnie zapisane",
    script: "Skrypt Grepolis GrepoTools",
    selectPage: "Wybierz stronę:",
    sendMessageAlliance: "Wyślij wiadomość do wszystkich członków sojuszu",
    sendMessageIsland:
      "Wyślij wiadomość do wszystkich członków sojuszu na wyspie",
    settings: "Ustawienia",
    show: "Pokaż",
    showInfoAboveTable: "Pokaż informacje poniżej nad tabelą",
    showInfoInTable: "Pokaż informacje poniżej w tabeli",
    silver: "Srebro",
    spellsHarborBarracks: "Zaklęcia w porcie i koszarach",
    stone: "Kamień",
    strategicMap: "Mapa strategiczna",
    text: "tekst",
    to: "Do",
    town: "Miasto",
    townName: "Nazwa miasta",
    townPoints: "Punkty miasta",
    towns: "Miasta",
    update: "Aktualizacja",
    version: "Wersja",
    whileScrolling: "podczas przewijania",
    wood: "Drewno",
    world: "Świat",

    colors: {
      blue: "niebieski",
      brown: "brązowy",
      green: "zielony",
      grey: "szary",
      lightblue: "jasnoniebieski",
      lightgreen: "jasnozielony",
      lightred: "jasnoczerwony",
      pink: "różowy",
      purple: "fioletowy",
      red: "czerwony",
      white: "biały",
      yellow: "żółty",
    },

    languages: {
      de: "Niemiecki",
      en: "Angielski",
      es: "Hiszpański",
      fr: "Francuski",
      gr: "Grecki",
      nl: "Holenderski",
      pl: "Polski",
      us: "Amerykański",
    },
  },

  es: {
    about: "Acerca de",
    active: "Activo",
    alliance: "Alianza",
    allianceDataAvailable: "Datos de la alianza disponibles. Alianza: ",
    allianceName: "Nombre de la alianza",
    allianceNumberPlayers: "Número de miembros de la alianza",
    alliancePoints: "Puntos de la alianza",
    allianceRank: "Rango de la alianza",
    and: "Y",
    attackNotification: "Animar el icono del navegador durante un ataque",
    battlePoints: "Puntos de batalla",
    bbcodeAlliance: "Copiar la información de todos los miembros de la alianza",
    bbcodeAllianceCopySucces: "BBCode - Información de la alianza copiada",
    bbcodeIsland: "Copiar la información de esta isla",
    bbcodeIslandCopyFail:
      "BBCode - La isla está vacía, la información no se copió",
    bbcodeIslandCopySucces: "BBCode - Información de la isla copiada",
    bbcodePlayer: "Copiar la información de este jugador",
    bbcodePlayerCopySucces: "BBCode - Información del jugador copiada",
    bbcodeWindowTitle: "GrepoTools - BBCode - Pegar datos",
    button: "Botón",
    changes: "Cambios",
    cityRequired:
      "La ciudad se agrega automáticamente, este campo es obligatorio",
    color: "Color",
    coordinates: "Coordenadas",
    day: "día",
    dayMode: "Modo día",
    days: "días",
    donation: "Donaciones",
    emptyColumn: "Columna vacía",
    farmerIslandNumbersTextColor:
      "Color del texto de los números de la isla del granjero",
    farmerVillageIslandNumbers: "Números de la isla del pueblo del granjero",
    farmerVillageIslandTags: "Etiquetas de la isla del pueblo del granjero",
    free: "Gratis",
    general: "General",
    ghostTown: "Ciudad fantasma",
    grepoTools: "GrepoTools",
    grepotoolsUpdateAvailable: "Actualización de Grepotools disponible",
    grepolisRank: "Rango de Grepolis",
    grepolisScore: "Puntuación de Grepolis",
    grid: "Cuadrícula",
    heroIcon: "Icono del héroe en la vista de la ciudad",
    hide: "Ocultar",
    hour: "hora",
    inactiveTimePlayer: "Inactividad del jugador (colaboración con GrepoData)",
    island: "Isla",
    islandDataAvailable: "Datos de la isla disponibles. Isla: ",
    islandEmptyNoMessage: "La isla está vacía, no se puede enviar un mensaje",
    islandInformationWindow: "Ventana de información de la isla",
    islandLinkIslandInfo:
      "números/etiquetas de la isla como enlace a la información de la isla",
    islandNoAllianceNoMessage:
      "No hay miembros de la alianza en esta isla, no se puede enviar un mensaje",
    islandNumber: "Número de la isla",
    islandNumbersTags: "Números / etiquetas de la isla",
    islandOccupation: "Ocupación de la isla",
    islandTag: "Etiqueta de la isla",
    islandView: "Vista de la isla",
    joinBetaTesting: "Unirse al programa de pruebas beta",
    language: "Idioma",
    mapTags: "Etiquetas del mapa",
    maxMembers: "Número máximo de miembros",
    member: "Miembro",
    members: "Miembros",
    message: "Mensaje",
    nightMode: "Modo nocturno",
    noDataAvailable: "GrepoTools BBCode - No hay datos disponibles",
    noWrap: "Mostrar etiquetas grandes en una línea",
    number: "Número",
    numberShort: "No",
    occupied: "Ocupado",
    ocean: "Océano",
    oceanGrid: "Cuadrícula del océano",
    oceanNumbers: "Números del océano",
    of: "De",
    otherScripts: "Otros scripts",
    page: "Página",
    pasteData: "Pegar datos",
    player: "Jugador",
    playerDataAvailable: "Datos del jugador disponibles. Jugador: ",
    playerName: "Nombre del jugador",
    playerRequired:
      "El jugador se agrega automáticamente, este campo es obligatorio",
    points: "Puntos",
    rank: "Rango",
    resources: "Recursos",
    rockIslandNumbers: "Números de la isla rocosa",
    rockIslandNumbersTextColor:
      "Color del texto de los números de la isla rocosa",
    safe: "Guardar",
    safeAndReload: "Guardar y recargar",
    safeFail: "La configuración de GrepoTools no se ha guardado correctamente",
    safeSuccess: "La configuración de GrepoTools se ha guardado correctamente",
    script: "Script de Grepolis GrepoTools",
    selectPage: "Seleccionar página:",
    sendMessageAlliance: "Enviar mensaje a todos los miembros de la alianza",
    sendMessageIsland:
      "Enviar mensaje a todos los miembros de la alianza en la isla",
    settings: "Configuraciones",
    show: "Mostrar",
    showInfoAboveTable: "Mostrar la información a continuación sobre la tabla",
    showInfoInTable: "Mostrar la información a continuación en la tabla",
    silver: "Plata",
    spellsHarborBarracks: "Hechizos en el puerto y cuarteles",
    stone: "Piedra",
    strategicMap: "Mapa estratégico",
    text: "texto",
    town: "Ciudad",
    to: "A",
    townName: "Nombre de la ciudad",
    townPoints: "Puntos de la ciudad",
    towns: "Ciudades",
    update: "Actualizar",
    version: "Versión",
    whileScrolling: "mientras se desplaza",
    wood: "Madera",
    world: "Mundo",

    colors: {
      blue: "azul",
      brown: "marrón",
      green: "verde",
      grey: "gris",
      lightblue: "azul claro",
      lightgreen: "verde claro",
      lightred: "rojo claro",
      pink: "rosa",
      purple: "púrpura",
      red: "rojo",
      white: "blanco",
      yellow: "amarillo",
    },

    languages: {
      de: "Alemán",
      en: "Inglés",
      es: "Español",
      fr: "Francés",
      gr: "Griego",
      nl: "Holandés",
      pl: "Polaco",
      us: "Americano",
    },
  },

  init() {
    language.loadSettings();

    if (
      !language.languages.includes(language.settingActiveLanguage) ||
      !language.settingActiveLanguage
    ) {
      language.settingActiveLanguage = "en";
    }

    language.us = language.en;
  },

  loadSettings() {
    const settingsKeys = [{ key: "settingActiveLanguage", default: "en" }];

    settingsKeys.forEach(({ key, default: defaultValue }) => {
      this[key] = settings.loadSetting(
        `${Game.world_id}|${this.module}.${key}`,
        defaultValue
      );
    });
  },

  safeSetting(setting) {
    const settingsKeys = {
      settingActiveLanguage: language.settingActiveLanguage,
    };

    if (settingsKeys.hasOwnProperty(setting)) {
      settings.safeSetting(
        `${Game.world_id}|${language.module}.${setting}`,
        settingsKeys[setting]
      );
    }
  },

  setActiveLanguage() {
    language.settingActiveLanguage = language.dropdownValueNewLanguage;
    language.safeSetting("settingActiveLanguage");

    HumanMessage.success(language[language.settingActiveLanguage].safeSuccess);

    setTimeout(function () {
      window.location.reload();
    }, 1000);
  },
};
